apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops.fullname" . }}
  labels:
    {{- include "aiops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aiops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops.fullname" . }}-worker
  labels:
    {{- include "aiops.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "aiops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 9910
      targetPort: metrics
